---
title: "Design Document"
author: "Adriana Souza, Roger Filmyer, Lydia LaSeur"
date: "April 14, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Your group will create a document (no page limit, approx. 1000-2000 words) summarizing the design process over the course of the project. Parts of the document will be written (text), but you will also need to include images and/or links demonstrating proposed design aspects.

Your paper should be well-written, and sources should be consistently cited. 

You will turn in a rough draft of the document during week 11. After that, you will get feedback from the instructor; you are welcome to resubmit a final draft of the document later in the semester (after your presentations). The rough draft is due prior to then in order to make sure you are considering design issues during the project creation (instead of getting too focused on technical issues). 

The structure of your paper should be as follows:

1. *Introduction and background:* what problem are you trying to solve or question are you trying to answer? What relevant resources already exist? Why is visualization an appropriate way to address this question (rather than statistical modeling, etc.)?

2. *Data and outcomes:* What is the structure of your data? Who is your intended audience/ users of the visualization? What tasks or features are the audience likely to need? Discuss this both generally and in terms of your data.

3. *Design process:* This is the longest section of the paper.

+ Give an overview of the different options (pros and cons) for displaying each type of information visually, and discuss why you chose the option you did. This should be repeated for each major element or grouping of your visualization product.
+ You should also discuss any challenges you ran into when implementing your design. For example, if you hoped to include a feature mentioned in your project proposal or peer review but weren’t able to get it to work, you should discuss what obstacles you encountered and what troubleshooting you attempted.
+ Discuss any feedback you received during the peer review process. If you are still in the process of including a feature, be honest about that. If you decided not to address some feedback from the peer review process, explain why.
+ Comment on if or how your goals and intended audience changed during the design process. 
+ This section should be a mixture of text and images of your designs. Please include screen shots or links as appropriate.

4. *Conclusion:* Summarize the goals and functionality of your final visualization product. What can your intended audience learn from your product? What did you learn? Describe any limitations of your current work and any future work you would like to include.

5. *Division of work:* A short summary of how the different tasks were split up among group members